// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Pendu
{

    internal class Liste
    {

        [JsonProperty("capitale")]
        public string Capitale { get; set; }

        [JsonProperty("accent")]
        public string Accent { get; set; }
    }

    internal class Répertoire
    {

        [JsonProperty("liste")]
        public Liste[] Liste { get; set; }
    }

}
